name: Build binary

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Release version (e.g., v2.0.0)"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.26.8"

      - name: Install dependencies
        run: |
          go mod tidy
          go mod download

      - name: Build binaries (amd64 + arm64)
        run: |
          set -e
          mkdir -p dist/linux dist/windows dist/android dist/darwin

          TARGETS=(
          "linux amd64"
          "linux arm64"
          "windows amd64"
          "windows arm64"
          "android arm64"
          "darwin arm64"
          )

          for t in "${TARGETS[@]}"; do
          read -r GOOS GOARCH <<< "$t"
          echo "Building for $GOOS/$GOARCH"
          ext=""
          outdir="dist/$GOOS"
          mkdir -p "$outdir"
          if [[ "$GOOS" == "windows" ]]; then ext=".exe"; fi

          CGO_ENABLED=0 GOOS=$GOOS GOARCH=$GOARCH \
            go build -ldflags="-s -w" -o "$outdir/wlc-${GOOS}-${GOARCH}${ext}" ./src/
          done
        shell: bash

      - name: Show built files
        run: ls -R dist
        shell: bash

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary-Windows
          path: dist/windows/*

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary-Linux
          path: dist/linux/*

      - name: Upload Android artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary-Android
          path: dist/android/*

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary-macOS
          path: dist/darwin/*

  merge-artifacts:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Windows binary
        uses: actions/download-artifact@v4
        with:
          name: binary-Windows
          path: combined-binaries

      - name: Download Linux binary
        uses: actions/download-artifact@v4
        with:
          name: binary-Linux
          path: combined-binaries

      - name: Download Android binary
        uses: actions/download-artifact@v4
        with:
          name: binary-Android
          path: combined-binaries

      - name: Download macOS binary
        uses: actions/download-artifact@v4
        with:
          name: binary-macOS
          path: combined-binaries

      - name: List combined contents
        run: ls -R combined-binaries
        shell: bash

      - name: Upload combined artifact
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ github.event.inputs.release_version }}
          path: combined-binaries
